version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matching-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 

volumes:
  postgres-data:
